// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdBanner: typeof import('./components/ad/AdBanner.vue')['default']
    ArrayBytesElement: typeof import('./components/dynamic/ArrayBytesElement.vue')['default']
    ArrayCoinElement: typeof import('./components/dynamic/ArrayCoinElement.vue')['default']
    ArrayElement: typeof import('./components/dynamic/ArrayElement.vue')['default']
    ArrayObjectElement: typeof import('./components/dynamic/ArrayObjectElement.vue')['default']
    ArrayStringElement: typeof import('./components/dynamic/ArrayStringElement.vue')['default']
    CardParameter: typeof import('./components/CardParameter.vue')['default']
    CardStatisticsVertical: typeof import('./components/CardStatisticsVertical.vue')['default']
    ChainSummary: typeof import('./components/ChainSummary.vue')['default']
    Countdown: typeof import('./components/Countdown.vue')['default']
    DonutChart: typeof import('./components/charts/DonutChart.vue')['default']
    DynamicComponent: typeof import('./components/dynamic/DynamicComponent.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IconWeb: typeof import('./components/icons/IconWeb.vue')['default']
    NumberElement: typeof import('./components/dynamic/NumberElement.vue')['default']
    ObjectElement: typeof import('./components/dynamic/ObjectElement.vue')['default']
    ObjectHorizontalElement: typeof import('./components/dynamic/ObjectHorizontalElement.vue')['default']
    PaginationBar: typeof import('./components/PaginationBar.vue')['default']
    PriceMarketChart: typeof import('./components/charts/PriceMarketChart.vue')['default']
    ProposalListItem: typeof import('./components/ProposalListItem.vue')['default']
    ProposalProcess: typeof import('./components/ProposalProcess.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextElement: typeof import('./components/dynamic/TextElement.vue')['default']
    TokenElement: typeof import('./components/dynamic/TokenElement.vue')['default']
    TxDialog: typeof import('./components/TxDialog.vue')['default']
    TxsElement: typeof import('./components/dynamic/TxsElement.vue')['default']
    TxsInBlocksChart: typeof import('./components/charts/TxsInBlocksChart.vue')['default']
    UInt8Array: typeof import('./components/dynamic/UInt8Array.vue')['default']
    UptimeBar: typeof import('./components/UptimeBar.vue')['default']
    ValidatorCommissionRate: typeof import('./components/ValidatorCommissionRate.vue')['default']
    WasmVerification: typeof import('./components/WasmVerification.vue')['default']
  }
}
